services:
  - type: web
    name: farm-ai
    env: docker
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /_stcore/health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: MONGO_USER
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_HOST
        sync: false
      - key: MONGO_PORT
        value: "27017"
